# Generated by Django 6.0.3 on 2026-03-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('TECHNICIAN', 'Field Technician'), ('RANGER', 'Park Ranger')], default='RANGER', max_length=20, verbose_name='User Role'),
        ),
    ]
