from rest_framework import viewsets

from telemetry.models import HealthStatus
from telemetry.models import SensorReading

from .serializers import HealthStatusSerializer
from .serializers import SensorReadingSerializer


class HealthStatusViewSet(viewsets.ReadOnlyModelViewSet):
    # Health statuses are generated by the ML pipeline, so they are read-only from the API
    queryset = HealthStatus.objects.all()
    serializer_class = HealthStatusSerializer
    
    queryset = HealthStatus.objects.all().order_by("-prediction_timestamp")
    serializer_class = HealthStatusSerializer

    def get_queryset(self):
        queryset = super().get_queryset()
        equipment = self.request.query_params.get("equipment")
        start_date = self.request.query_params.get("start_date")
        end_date = self.request.query_params.get("end_date")

        if equipment:
            queryset = queryset.filter(equipment_id=equipment)
        if start_date:
            queryset = queryset.filter(prediction_timestamp__gte=start_date)
        if end_date:
            queryset = queryset.filter(prediction_timestamp__lte=end_date)
            
        return queryset

class SensorReadingViewSet(viewsets.ReadOnlyModelViewSet):
    # Readings are ingested via MQTT/Celery worker, so read-only for API access typically
    queryset = SensorReading.objects.all()
    serializer_class = SensorReadingSerializer
