# Generated by Django 6.0.3 on 2026-03-21 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_score', models.FloatField(verbose_name='Anomaly Score')),
                ('status', models.CharField(choices=[('NORMAL', 'Normal'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], db_index=True, default='NORMAL', max_length=10)),
                ('prediction_timestamp', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_assessments', to='inventory.equipment')),
            ],
            options={
                'verbose_name': 'Health Status',
                'verbose_name_plural': 'Health Statuses',
                'ordering': ['-prediction_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='Temperature (°C)')),
                ('voltage', models.FloatField(verbose_name='Voltage (Vrms)')),
                ('vib_x', models.FloatField(verbose_name='Vibration X (G)')),
                ('vib_y', models.FloatField(verbose_name='Vibration Y (G)')),
                ('vib_z', models.FloatField(verbose_name='Vibration Z (G)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='inventory.equipment')),
            ],
            options={
                'verbose_name': 'Sensor Reading',
                'verbose_name_plural': 'Sensor Readings',
                'ordering': ['-timestamp'],
            },
        ),
    ]
